build_platform: {osx_arm64: osx_64, linux_ppc64le: linux_64, linux_aarch64: linux_64, win_arm64: win_arm64}
provider: {linux_aarch64: default, linux_ppc64le: default, win_arm64: github_actions}
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  self_hosted: true
  triggers:
    - push
    - pull_request
conda_build:
  pkg_format: '2'
